# --- FMAC specific parameters ---

# use epsilon greedy action selector
action_selector: "gumbel"
epsilon_start: .0
epsilon_finish: .0
epsilon_anneal_time: 100000
mask_before_softmax: True

mac: 'lica_mac'

runner: "parallel"
batch_size_run: 8
buffer_size: 1000
batch_size: 64

t_max: 10050000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "pi_logits"

learner: "fmac_learner"
mixer: "qmix"
mixing_embed_dim: 32
hypernet_embed: 64

lr: 0.001 # Learning rate for agents
critic_lr: 0.0005
lambd: 0.5
entropy_coef: 0.05
optimizer: 'adam'

name: "fmaddpg_env=8_adam_td_lambda"
